baseURL: http://example.org/
languageCode: pl_PL
title: dariusz.blog
theme: "PaperMod"

params:
    homeInfoParams:
        Title: CzeÅ›Ä‡... ğŸ‘‹ ğŸ‘ ğŸ™‚ 
        Content: CieszÄ™ siÄ™, Å¼e tu jesteÅ›. Ten blog jest o **prawach czÅ‚owieka, edukacji, technologii, mÅ‚odych ludziach** i wielu innych tematach, ktÃ³rymi siÄ™ interesujÄ™. MiÅ‚ego czytania! 
